# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2483365750" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/2483365750/vehicles/{VehicleId}.png" # The repository of the override.