# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1905768396" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/1905768396/vehicles/{VehicleId}.png" # The repository of the override.